INSERT INTO STC_SITUACAO_CONTA (STC_CODIGO, STC_TIPO) VALUES (0, 'AGUARDANDO CONFIRMAÇÃO');
INSERT INTO STC_SITUACAO_CONTA (STC_CODIGO, STC_TIPO) VALUES (1, 'ATIVA');
INSERT INTO STC_SITUACAO_CONTA (STC_CODIGO, STC_TIPO) VALUES (2, 'INATIVA');
INSERT INTO STC_SITUACAO_CONTA (STC_CODIGO, STC_TIPO) VALUES (3, 'BANIDA');
