CREATE TABLE AMG_AMIGOS (
	AMG_SEGUIDOR INTEGER,
	AMG_SEGUIDO INTEGER
);

ALTER TABLE AMG_AMIGOS ADD CONSTRAINT AMG_PK PRIMARY KEY (AMG_SEGUIDOR, AMG_SEGUIDO);
ALTER TABLE AMG_AMIGOS ADD CONSTRAINT AMG_USR_SEGUIDOR FOREIGN KEY (AMG_SEGUIDOR) REFERENCES USR_USUARIO (USR_CODIGO);
ALTER TABLE AMG_AMIGOS ADD CONSTRAINT AMG_USR_SEGUIDO FOREIGN KEY (AMG_SEGUIDO) REFERENCES USR_USUARIO (USR_CODIGO);