CREATE TABLE EML_EMAIL
(
	EML_CODIGO 		NUMBER NOT NULL,
	EML_REMETENTE 	VARCHAR2 (200) NOT NULL,
	EML_ASSUNTO 	VARCHAR2 (2000) NOT NULL,
	EML_MENSAGEM 	VARCHAR2 (2000) NOT NULL
);

ALTER TABLE EML_EMAIL			ADD CONSTRAINT EML_PK PRIMARY KEY (EML_CODIGO);