ALTER TABLE USR_USUARIO ADD USR_DT_INSRT DATE;
ALTER TABLE USR_USUARIO DROP COLUMN USR_TPC_TIPO_CONEXAO;
ALTER TABLE USR_USUARIO DROP COLUMN USR_CAD_CONFIRM;

DROP TABLE TPC_TIPO_CONEXAO;

INSERT INTO STC_SITUACAO_CONTA VALUES (0, 'AGUARDANDO_CONFIRMACAO');
INSERT INTO STC_SITUACAO_CONTA VALUES (3, 'BANIDA');
