CREATE TABLE USD_USUARIO_DETALHE
(
	USD_USR_CODIGO 	NUMBER NOT NULL,
	USD_NICKNAME 	VARCHAR2 (200) NOT NULL,
	USD_NOME 		VARCHAR2 (200) NOT NULL,
	USD_DATA_NASC 	DATE NOT NULL,
	USD_CIDADE 		VARCHAR2 (200) NOT NULL,
	USD_ESTADO 		VARCHAR2 (200) NOT NULL,
	USD_PAIS 		VARCHAR2 (200) NOT NULL
);

ALTER TABLE USD_USUARIO_DETALHE ADD CONSTRAINT USD_PK PRIMARY KEY (USD__USR_CODIGO);

ALTER TABLE USD_USUARIO_DETALHE ADD 	CONSTRAINT USD_X_USR_FK FOREIGN KEY (USD_USR_CODIGO)			REFERENCES USR_USUARIO (USR_CODIGO);