CREATE TABLE USR_USUARIO 
(
	USR_CODIGO 				NUMBER NOT NULL,
	USR_EMAIL 				VARCHAR2 (200) NOT NULL,
	USR_SENHA 				VARCHAR2 (200) NOT NULL,
	USR_NVU_NIVEL_USUARIO	NUMBER NOT NULL,
	USR_TPC_TIPO_CONEXAO 	NUMBER NOT NULL,
	USR_STC_SITUACAO_CONTA  NUMBER NOT NULL,
	USR_COD_CONEXAO 		VARCHAR2 (200)
);

ALTER TABLE USR_USUARIO 		ADD CONSTRAINT USR_PK PRIMARY KEY (USR_CODIGO);

ALTER TABLE USR_USUARIO			ADD 	CONSTRAINT USR_X_NVU_FK	FOREIGN KEY (USR_NVU_NIVEL_USUARIO) 		REFERENCES NVU_NIVEL_USUARIO (NVU_CODIGO);
ALTER TABLE USR_USUARIO			ADD 	CONSTRAINT USR_X_TPC_FK	FOREIGN KEY (USR_TPC_TIPO_CONEXAO)	 	REFERENCES TPC_TIPO_CONEXAO (TPC_CODIGO);
ALTER TABLE USR_USUARIO			ADD 	CONSTRAINT USR_X_STC_FK	FOREIGN KEY (USR_STC_SITUACAO_CONTA) 	REFERENCES STC_SITUACAO_CONTA (STC_CODIGO);

ALTER TABLE USR_USUARIO ADD CONSTRAINT USR_COD_CONEXAO_UK UNIQUE (USR_COD_CONEXAO);